export const reviews = [
  // Original Reviews
  { username: 'John.pact2', text: 'Thought this was useless but had it for a week 2 and I can definitely feel and see some change. I salute ✅' },
  { username: 'MikeT', text: 'Surprisingly effective. Was skeptical at first but the science makes sense. Seeing progress.' },
  { username: 'AnonymousUser1', text: 'Best $10 I\'ve ever spent. Seriously. Just follow the steps and be patient.' },
  { username: 'GrowthSeeker', text: 'It\'s not magic, it\'s biology. The video explains it perfectly. Trust the process.' },
  { username: 'David_R', text: 'Two weeks in and the difference is noticeable. My confidence is through the roof.' },
  { username: 'Alex_B', text: 'Simple, easy to follow, and it actually works. No weird pills or gadgets. 10/10.' },
  { username: 'SkepticalSam', text: 'I was wrong. This thing works. Give it a try, you won\'t regret it.' },
  { username: 'FutureMeThanksMe', text: 'My only regret is not finding this sooner. Game changer.' },
  { username: 'TomJ', text: 'Clear instructions and based on real science. Glad I took the leap.' },
  { username: 'BetterMan', text: 'This is the real deal. No hype, just results. Stick with it.' },
  // New Reviews
  { username: 'WOOOW! 🤯', text: 'Ok, I\'m only on day 5 but I swear I\'m already seeing a difference. This is wild. GET THIS NOW! 🔥🔥' },
  { username: 'BRO.', text: 'This actually works. I\'m stoked. I\'ve been doing it for 3 weeks and it\'s a legit, noticeable change. YES! 💯' },
  { username: 'Skeptic (Now Convinced)', text: 'Was 99% sure this was gonna be a scam for $10. Glad to be wrong. It\'s subtle, but it\'s definitely working. Respect.' },
  { username: 'Logical/Analytical', text: 'I rolled my eyes so hard when I bought this, fully expecting nothing. Well, joke\'s on me. This is the real deal. It’s not magic, it’s just a solid method.' },
  { username: 'Makes Sense', text: 'The biology part just... makes sense. It\'s not magic, it\'s just physiology they don\'t teach us. The 11-minute video explains the \'why\' and \'how\' perfectly. Solid information.' },
  { username: 'Hidden Knowledge', text: 'This is the \'hidden knowledge\' I\'ve been looking for. It\'s not about pills or weird gadgets, it\'s about understanding your own body. The 2-step system is logical and, more importantly, effective.' },
  { username: 'Brief & Nonchalant', text: 'Yeah, it\'s pretty solid. Watched the video, it\'s straightforward. Not bad for 10 bucks.' },
  { username: 'Simple', text: 'It works. Simple.' },
  { username: 'Good Info', text: 'Good info. Worth the price.' },
  { username: 'Immediate Action-Taker', text: 'Just finished the video. Seems way too simple, but I\'m trying this out now. The explanation makes sense, so we\'ll see. Following the steps starting today.' },
  { username: 'Optimistic', text: 'Just bought it. Video was super clear and easy to understand. Feeling really optimistic about this! Seems legit. 🤞' },
  { username: 'Community Member', text: 'Been following @big_gentlemen_club on Insta for a while, dude knows his stuff. Pulled the trigger on this and it\'s exactly the no-hype, real info I expected. Yes, I follow, and you should too.' },
  { username: 'IG Follower', text: 'Heard about this from his IG. The video is straight to the point, no fluff, just like his posts. This is the info I’ve been missing.' },
  { username: 'Value for Money', text: 'Ten bucks is a steal for this. Seriously. I\'ve spent way more on useless junk. Glad to get in on this. Best $10 I\'ve spent all year.' },
  { username: 'Best $10', text: 'Best $10 I\'ve ever spent. Period. The confidence boost alone is worth 10x that.' },
  { username: 'Long-Form Reviewer', text: 'Okay, so I was hesitant. We\'ve all seen the crazy ads. But this is different. It\'s a 2-step *process*. I\'ve been doing it for three weeks. The first week, nothing. Then, like the original review said, week 2... you just feel it. It\'s firmer, hangs better. It\'s not magic overnight, but it\'s steady progress. Trust the process.' },
  { username: 'Honest Review', text: 'Honestly, I didn\'t know why I never heard of this specific method before. I\'ve tried pumps, pills, extenders... all garbage. This is the *only* thing that has ever produced a real, natural change. It’s all about consistency. Thank you for this. 🙏' },
  { username: 'Partner Noticed', text: 'Ngl my girl is the one who told me to write this. She... uh... noticed. 😅 So yeah, two thumbs up.' },
  { username: 'Grateful', text: 'Man, thank you. Seriously. This little video contained such useful information. It’s not a gimmick, it’s just... correct. Changed a lot for me.' },
  { username: 'Hopeful', text: 'I\'ve been insecure about this for years. This is the first method that\'s ever felt right and given me hope. It’s working. Thank you.' },
];
